version: "3"
services:
  rabbit-server:
    image: rabbitmq:3-management
    container_name: rabbit-server
    ports:
      - "5672:5672"
      - "15672:15672"
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "3000:9000"
      - "3001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - /blob-storage:/data
    command: server /data --console-address ":9001"
